
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace prjWantWantWinForm
{

using System;
    using System.Collections.Generic;
    
public partial class MemberAccount
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public MemberAccount()
    {

        this.CheckIns = new HashSet<CheckIn>();

        this.ExpertAccounts = new HashSet<ExpertAccount>();

        this.ExpertApplications = new HashSet<ExpertApplication>();

        this.ForgetPasswords = new HashSet<ForgetPassword>();

        this.ForumPosts = new HashSet<ForumPost>();

        this.ForumPostComments = new HashSet<ForumPostComment>();

        this.LoginHistories = new HashSet<LoginHistory>();

        this.MemberCollections = new HashSet<MemberCollection>();

        this.MemberRoleConns = new HashSet<MemberRoleConn>();

        this.MemberStatusLists = new HashSet<MemberStatusList>();

        this.Orders = new HashSet<Order>();

        this.Resumes = new HashSet<Resume>();

        this.ServiceContacts = new HashSet<ServiceContact>();

    }


    public int AccountID { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public bool AccountStatus { get; set; }

    public int MemberTotalPoint { get; set; }

    public System.DateTime CreateTime { get; set; }

    public string IDCardNo { get; set; }

    public string Name { get; set; }

    public string Gender { get; set; }

    public string UserName { get; set; }

    public Nullable<System.DateTime> BitrhDay { get; set; }

    public string PhoneNo { get; set; }

    public byte[] MemberPhoto { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CheckIn> CheckIns { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ExpertAccount> ExpertAccounts { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ExpertApplication> ExpertApplications { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ForgetPassword> ForgetPasswords { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ForumPost> ForumPosts { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ForumPostComment> ForumPostComments { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LoginHistory> LoginHistories { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MemberCollection> MemberCollections { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MemberRoleConn> MemberRoleConns { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MemberStatusList> MemberStatusLists { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Order> Orders { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Resume> Resumes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ServiceContact> ServiceContacts { get; set; }

}

}
