
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace prjWantWantWinForm
{

using System;
    using System.Collections.Generic;
    
public partial class Resume
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Resume()
    {

        this.MemberCollections = new HashSet<MemberCollection>();

        this.ResumeApplications = new HashSet<ResumeApplication>();

        this.ResumeCertificates = new HashSet<ResumeCertificate>();

        this.ResumeKeywordLists = new HashSet<ResumeKeywordList>();

        this.ResumeSkills = new HashSet<ResumeSkill>();

        this.OrderDetails = new HashSet<OrderDetail>();

        this.ApplicationLists = new HashSet<ApplicationList>();

    }


    public int AccountID { get; set; }

    public int ResumeID { get; set; }

    public Nullable<int> TownID { get; set; }

    public string Address { get; set; }

    public string Autobiography { get; set; }

    public Nullable<int> WorkingHoursID { get; set; }

    public byte[] Photo { get; set; }

    public Nullable<int> OnTop { get; set; }

    public Nullable<int> TaskNameID { get; set; }



    public virtual ExpertResume ExpertResume { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MemberCollection> MemberCollections { get; set; }

    public virtual Town Town { get; set; }

    public virtual WorkingTime WorkingTime { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ResumeApplication> ResumeApplications { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ResumeCertificate> ResumeCertificates { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ResumeKeywordList> ResumeKeywordLists { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ResumeSkill> ResumeSkills { get; set; }

    public virtual TaskNameList TaskNameList { get; set; }

    public virtual MemberAccount MemberAccount { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrderDetail> OrderDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ApplicationList> ApplicationLists { get; set; }

}

}
