
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace prjWantWantWinForm
{

using System;
    using System.Collections.Generic;
    
public partial class TaskList
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TaskList()
    {

        this.CaseSkills = new HashSet<CaseSkill>();

        this.ExpertApplications = new HashSet<ExpertApplication>();

        this.ExpertTasks = new HashSet<ExpertTask>();

        this.MemberCollections = new HashSet<MemberCollection>();

        this.TaskKeywordLists = new HashSet<TaskKeywordList>();

        this.OrderDetails = new HashSet<OrderDetail>();

        this.ApplicationLists = new HashSet<ApplicationList>();

    }


    public int CaseID { get; set; }

    public Nullable<int> AccountID { get; set; }

    public Nullable<int> TaskNameID { get; set; }

    public string TaskTitle { get; set; }

    public string TaskDetail { get; set; }

    public Nullable<int> TeachToID { get; set; }

    public Nullable<int> WorkingHoursID { get; set; }

    public string PayFrom { get; set; }

    public string PayTo { get; set; }

    public Nullable<int> SalaryID { get; set; }

    public Nullable<int> TaskPlace { get; set; }

    public Nullable<int> TownID { get; set; }

    public string Address { get; set; }

    public string RequiredNum { get; set; }

    public string TaskPeriod { get; set; }

    public string TaskStart { get; set; }

    public string TaskEnd { get; set; }

    public string Requirement { get; set; }

    public string HumanList { get; set; }

    public string LanguageRequired { get; set; }

    public string SkillRequiredID { get; set; }

    public string CertificateRequiredID { get; set; }

    public Nullable<bool> ServiceStatus { get; set; }

    public Nullable<int> StatusChangeReasonID { get; set; }

    public string PublishStart { get; set; }

    public string PublishEnd { get; set; }

    public Nullable<int> CaseStatusID { get; set; }

    public Nullable<int> TaskPhotoID { get; set; }

    public Nullable<int> OnTop { get; set; }

    public string DataCreateDate { get; set; }

    public string DataModifyDate { get; set; }

    public string DataModifyPerson { get; set; }

    public string WorkPlace { get; set; }

    public string PublishOrNot { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CaseSkill> CaseSkills { get; set; }

    public virtual CaseStatusList CaseStatusList { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ExpertApplication> ExpertApplications { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ExpertTask> ExpertTasks { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MemberCollection> MemberCollections { get; set; }

    public virtual Salary Salary { get; set; }

    public virtual StatusChangeReason StatusChangeReason { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TaskKeywordList> TaskKeywordLists { get; set; }

    public virtual TaskNameList TaskNameList { get; set; }

    public virtual TaskPhoto TaskPhoto { get; set; }

    public virtual TeachToList TeachToList { get; set; }

    public virtual Town Town { get; set; }

    public virtual WorkingTime WorkingTime { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrderDetail> OrderDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ApplicationList> ApplicationLists { get; set; }

}

}
