

//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace prjWantWantWinForm
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class NewIspanProjectEntities : DbContext
{
    public NewIspanProjectEntities()
        : base("name=NewIspanProjectEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<CaseSkill> CaseSkills { get; set; }

    public virtual DbSet<CaseStatusList> CaseStatusLists { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Certificate> Certificates { get; set; }

    public virtual DbSet<CertificateType> CertificateTypes { get; set; }

    public virtual DbSet<CheckIn> CheckIns { get; set; }

    public virtual DbSet<City> Cities { get; set; }

    public virtual DbSet<ExpertAccount> ExpertAccounts { get; set; }

    public virtual DbSet<ExpertApplication> ExpertApplications { get; set; }

    public virtual DbSet<ExpertResume> ExpertResumes { get; set; }

    public virtual DbSet<ExpertTask> ExpertTasks { get; set; }

    public virtual DbSet<ExpertWorkList> ExpertWorkLists { get; set; }

    public virtual DbSet<ExpertWork> ExpertWorks { get; set; }

    public virtual DbSet<ForgetPassword> ForgetPasswords { get; set; }

    public virtual DbSet<ForumCategory> ForumCategories { get; set; }

    public virtual DbSet<ForumPost> ForumPosts { get; set; }

    public virtual DbSet<ForumPostCategory> ForumPostCategories { get; set; }

    public virtual DbSet<ForumPostComment> ForumPostComments { get; set; }

    public virtual DbSet<ForumStatu> ForumStatus { get; set; }

    public virtual DbSet<Keyword> Keywords { get; set; }

    public virtual DbSet<LoginHistory> LoginHistories { get; set; }

    public virtual DbSet<MemberAccount> MemberAccounts { get; set; }

    public virtual DbSet<MemberCollection> MemberCollections { get; set; }

    public virtual DbSet<MemberRoleConn> MemberRoleConns { get; set; }

    public virtual DbSet<MemberStatusList> MemberStatusLists { get; set; }

    public virtual DbSet<PayWay> PayWays { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<ProductPhoto> ProductPhotoes { get; set; }

    public virtual DbSet<Rating> Ratings { get; set; }

    public virtual DbSet<Resume> Resumes { get; set; }

    public virtual DbSet<ResumeApplication> ResumeApplications { get; set; }

    public virtual DbSet<ResumeCertificate> ResumeCertificates { get; set; }

    public virtual DbSet<ResumeKeywordList> ResumeKeywordLists { get; set; }

    public virtual DbSet<ResumeSkill> ResumeSkills { get; set; }

    public virtual DbSet<RoleInfo> RoleInfoes { get; set; }

    public virtual DbSet<Salary> Salaries { get; set; }

    public virtual DbSet<Skill> Skills { get; set; }

    public virtual DbSet<SkillType> SkillTypes { get; set; }

    public virtual DbSet<StatusChangeReason> StatusChangeReasons { get; set; }

    public virtual DbSet<sysdiagram> sysdiagrams { get; set; }

    public virtual DbSet<TaskKeywordList> TaskKeywordLists { get; set; }

    public virtual DbSet<TaskList> TaskLists { get; set; }

    public virtual DbSet<TaskNameList> TaskNameLists { get; set; }

    public virtual DbSet<TaskPhoto> TaskPhotoes { get; set; }

    public virtual DbSet<TeachToList> TeachToLists { get; set; }

    public virtual DbSet<Town> Towns { get; set; }

    public virtual DbSet<WorkingTime> WorkingTimes { get; set; }

    public virtual DbSet<HumanList> HumanLists { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderDetail> OrderDetails { get; set; }

    public virtual DbSet<ServiceContact> ServiceContacts { get; set; }

    public virtual DbSet<ApplicationList> ApplicationLists { get; set; }

}

}

